app/actors/LevelGenerationActor.scala, app/actors/SocketResponseConvertFlow.scala, app/actors/messages/ClientRobotState.scala, app/actors/messages/PreparedStepData.scala, app/controllers/MathBotCompiler.scala, conf/assets/BasicProgramming.json, ui/.eslintrc.js, ui/package-lock.json, ui/src/components/Commands.vue, ui/src/components/Edit_main.vue, ui/src/components/Grid.vue, ui/src/components/Robot.vue, ui/src/services/GridAnimator.js, ui/src/services/RobotState.js, ui/src/services/RunCompiled.js, ui/src/store/store.js
Robot animates as expected, without pause/stop button.
=> Ask compiler

app/actors/LevelGenerationActor.scala
=> v0.02-alpha

app/actors/CompilerActor.scala, conf/application.conf, conf/logback.xml
Shut down the mongo db client spam.
Raises the log noise for akka.
=> Fixed "empty function" bug.

conf/assets/Recursion.json, ui/config/index.js, ui/src/components/Edit_function.vue, ui/src/router/index.js
=> Disables color feature for all levels before conditionals

conf/assets/Recursion.json, ui/src/components/Commands.vue
=> Resolves issue #207

conf/assets/Conditionals.json, conf/assets/Recursion.json, ui/src/components/Control_panel.vue
=> Adds missing videos to conditionals. Updates recursion level 14 videos for new board layout.

ui/src/components/Grid.vue, ui/src/components/Robot.vue, ui/src/components/Video_hint.vue
=> implements black background for video hints #292

ui/src/components/Steps.vue
=> #301 adds height to step containers parent

ui/src/components/Control_panel.vue, ui/src/components/Stars.vue
=> replaces hint time remaining with a bootstrap progress bar

ui/src/components/Activate_drop.vue, ui/src/components/Staged_functions.vue
=> allows staged functions to be dropped anywhere to be activated

app/actors/messages/BounceRecords.scala, app/actors/messages/DeleteBounce.scala, app/actors/messages/EmailBounceCheck.scala, app/actors/messages/EmailBounceNotification.scala, app/actors/messages/MailFailed.scala, app/actors/messages/MailSent.scala
Adds password recovery endpoints
=> Additional messages to support SendGridActor

ui/src/components/Grid.vue
=> solution for #302

ui/src/components/Congrats.vue, ui/src/components/Control_panel.vue, ui/src/components/Grid.vue, ui/src/components/Stars.vue, ui/src/components/Video_hint.vue, ui/src/services/VideoHint.js, ui/src/store/store.js
=> Video hints are inside a bootstrap modal

ui/src/components/Video_hint.vue
=> removes suggested videos from embedded hints

conf/assets/Conditionals.json, ui/src/components/Control_panel.vue, ui/src/components/Profile.vue, ui/src/components/Social_sharing.vue, ui/src/components/Step_congrats.vue, ui/src/components/Video_hint.vue, ui/src/services/RunCompiled.js, ui/src/services/VideoHint.js
=> Makes the first hint free once when a user loads Conditionals/1. Also makes videos play properly.

ui/src/components/Control_panel.vue, ui/src/components/Mascot.vue, ui/src/components/User_profile_controls.vue, ui/src/components/marketing/TopSection.vue
=> implements animated mascot

ui/src/components/Puzzle_pieces.vue
=> makes font size larger in puzzle pieces

ui/src/components/Puzzle_pieces.vue, ui/src/services/BuildFunction.js
=> resizes puzzle piece font based on longest word

app/actors/PlayerActor.scala, ui/src/components/Edit_function.vue, ui/src/components/Puzzle_pieces.vue, ui/src/services/AuthService.js
=> puzzle piece text will stay inside puzzle pieces

ui/src/components/Puzzle_pieces.vue
=> ensures puzzle text is correct size on reload

ui/src/services/AuthService.js
=> removes unneeded console log

ui/src/components/Puzzle_pieces.vue
=> adds a condtion checkout if the name field is defined in puzzle pieces

ui/src/components/Social_sharing.vue
=> reformats social text

ui/src/components/Confirm_deactivate_func.vue, ui/src/components/Control_bar.vue, ui/src/components/Robot.vue
#487 @j-chimienti Work looks great! I just made a few changes related to code style, nothing major. A cool feature in Vue is that it converts camel case into proper html syntax, checkout my change in Robot.vue.
I did see one bug, when I click the trash icon on the bar the pieces animate properly but when I click the x to leave they continue to animate.
=> fixes code style issues and bugs related to diverging work

ui/package-lock.json, ui/src/components/Robot.vue, ui/src/components/Staged_functions.vue
=> Moves activate function component to robot component.

app/actors/messages/level/ContinentControl.scala, app/level_gen/continents/Coordinates.scala, ui/src/services/CompilerControl.js, ui/src/services/RobotState.js, ui/src/services/RunCompiled.js
=> adjusts coordinates grid locations

app/actors/LevelControl.scala, app/actors/messages/level/Stats.scala, ui/src/services/LevelControl.js
=> Star system

ui/src/components/Continents.vue
=> replaces selected continent gradient with 2px border

app/level_gen/continents/Multiplication.scala, ui/src/eventBus.js, ui/src/example-keys.js
=> changes multiplication 1 problem to 2 * 2. prunes keys from ui

app/level_gen/continents/Multiplication.scala
=> changes multiplication 2 problem to 3 * 2. prunes keys from ui

app/actors/messages/level/Function.scala, app/actors/messages/level/PreparedFunctions.scala, ui/src/components/Commands.vue, ui/src/components/Confirm_deactivate_func.vue, ui/src/components/Control_bar.vue, ui/src/components/Edit_function.vue, ui/src/components/Edit_main.vue, ui/src/components/Staged_functions.vue
=> Ensures correct functions is sent for deactivation. Fixes put settings when a function is full

app/level_gen/continents/Coordinates.scala
=> adds levels to coordinates

ui/src/App.vue, ui/src/components/Control_bar.vue, ui/src/services/RunCompiled.js
=> makes failure animations more subtle and obvious

ui/src/components/Edit_function.vue, ui/src/components/Puzzle_pieces.vue
=> uses vmin for sizing text inside pieces

app/level_gen/continents/Addition.scala, app/level_gen/continents/Coordinates.scala, app/level_gen/continents/Division.scala, app/level_gen/continents/Exponents.scala, app/level_gen/continents/Multiplication.scala, app/level_gen/continents/Roots.scala, app/level_gen/continents/Subtraction.scala
=> adds hints to single digit arithmetic levels

ui/src/components/Confirm_deactivate_func.vue, ui/src/components/Function_box.vue, ui/src/components/Puzzle_pieces.vue
=> makes puzzle piece bigger in confirm deactivate func component

app/actors/messages/level/PreparedFunctions.scala, ui/src/services/FunctionHighlighter.js, ui/src/services/LevelControl.js
=> Loads new staged functions on load, debugs staged functions add/trim functions.

app/level_gen/continents/Addition.scala, app/level_gen/continents/Coordinates.scala, app/level_gen/continents/Division.scala, app/level_gen/continents/Exponents.scala, app/level_gen/continents/Multiplication.scala, app/level_gen/continents/Roots.scala, app/level_gen/continents/Subtraction.scala
=> adds free hints to single digit arithmetic planets

app/level_gen/continents/Coordinates.scala
=> updates first free hint of arithmetic

app/actors/VideoHintActor.scala
=> resets stars to 3 after video wait time expires

app/actors/messages/level/BuiltContinent.scala, app/actors/messages/level/Functions.scala, app/actors/messages/level/PreparedFunctions.scala, ui/src/services/LevelControl.js
=> fixes sorting bug in second apply method in prepared functions class

app/actors/messages/level/PreparedFunctions.scala, ui/src/components/Control_panel.vue
=> Removes sortBy from main function

ui/src/App.vue, ui/src/assets/assets.js, ui/src/components/Control_bar.vue, ui/src/services/GridAnimator.js, ui/src/services/RobotState.js, ui/src/services/RunCompiled.js
=> robot can move forward and backward

ui/src/App.vue, ui/src/components/Edit_main.vue
=> Scrub through ui mvp

ui/src/components/Grid_controls.vue, ui/src/services/RunCompiled.js
=> Makes speed center pause activate pause

app/actors/LevelActor.scala, app/actors/LevelControl.scala, ui/src/components/Edit_function.vue, ui/src/components/Edit_main.vue
=> fixes client init so that only a single stats doc is added for a legacy user. ensures put is correct in edit main and edit function.

app/level_gen/Continents.scala, app/level_gen/Planets.scala, app/level_gen/StarSystems.scala
=> removes sandbox

app/actors/CompilerActor.scala, app/actors/LevelControl.scala, app/actors/messages/level/DefaultFunctions.scala, app/actors/messages/level/Functions.scala, app/actors/messages/level/PreparedFunctions.scala, app/level_gen/README.md, app/level_gen/continents/Addition.scala, app/level_gen/continents/BasicProgramming.scala, app/level_gen/continents/Conditionals.scala, app/level_gen/continents/Coordinates.scala, app/level_gen/continents/Counting.scala, app/level_gen/continents/Division.scala, app/level_gen/continents/Exponents.scala, app/level_gen/continents/Multiplication.scala, app/level_gen/continents/Numbers.scala, app/level_gen/continents/Recursion.scala, app/level_gen/continents/Roots.scala, app/level_gen/continents/Subtraction.scala, app/level_gen/models/ContinentStruct.scala, app/level_gen/sandbox/Sandbox.scala, ui/src/components/Activate_drop.vue, ui/src/components/Commands.vue, ui/src/components/Confirm_deactivate_func.vue, ui/src/components/Edit_function.vue, ui/src/components/Function_box.vue, ui/src/components/Grid_controls.vue, ui/src/components/Puzzle_pieces.vue, ui/src/components/Staged_functions.vue, ui/src/services/LevelControl.js, ui/src/services/RunCompiled.js
=> New ui is mvp, ready for inspection

ui/src/components/Commands.vue, ui/src/components/Edit_function.vue, ui/src/components/Edit_main.vue, ui/src/components/Staged_functions.vue, ui/src/services/ScrollOptions.js
=> Prunes ui components, widens scroll area in functions component.

app/actors/messages/level/Stats.scala, app/daos/StatsDAO.scala, app/level_gen/Planets.scala, ui/src/components/Admin_level_stats.vue
=> Implements maxContinent in user_stats

app/actors/messages/level/Stats.scala, app/daos/StatsDAO.scala
=> evaluates max continent path more efficently

app/daos/PlayerAccountDAO.scala, app/daos/PlayerTokenDAO.scala, app/daos/StatsDAO.scala, app/daos/VideoHintDAO.scala, app/loggers/SemanticLog.scala
Implements indexing portion of #704
=> implements indexing on stats, player token and video hint daos

ui/src/components/Profile.vue, ui/src/components/Splash_screen.vue, ui/src/components/Star_system.vue
Implements splash screen for #704
=> implements splash screen on profile page

app/actors/LevelActor.scala, app/actors/LevelControl.scala, app/actors/PlayerAccountActor.scala, app/actors/convert_flow/LevelRequestConvertFlow.scala, app/actors/messages/auth/SessionAuthorized.scala, app/actors/messages/playeraccount/GetLastCacheId.scala, app/actors/messages/playeraccount/UpdateCacheId.scala, app/controllers/AuthController.scala, app/controllers/LevelController.scala, app/daos/PlayerAccountDAO.scala, app/models/PlayerAccount.scala, ui/index.html, ui/src/assets/assets.js, ui/src/components/Auth.vue, ui/src/components/Planets.vue, ui/src/services/AuthService.js, ui/src/services/LevelControl.js, ui/src/store/store.js
=> Caches profile data on client if session id matches last cache id

ui/src/services/LevelControl.js
=> adds back unload for profile data, works

ui/src/components/Continents.vue, ui/src/components/Control_panel.vue, ui/src/components/Planets.vue, ui/src/components/Profile.vue, ui/src/components/Star.vue, ui/src/components/Star_system.vue, ui/src/components/Stars.vue, ui/src/services/LevelControl.js
=> Updates star-system buttons

ui/src/components/Confirm_deactivate_func.vue, ui/src/components/Continent_congrats.vue, ui/src/components/Staged_functions.vue, ui/src/components/Stars.vue, ui/src/services/LevelControl.js
=> Prevents commands from being deactivated

conf/application.conf, ui/src/components/User_profile_controls.vue
=> references env for admin callbacks if exists

ui/src/components/Admin.vue, ui/src/components/Admin_max_level.vue, ui/src/components/UserSignupsPerDayChart.vue, ui/src/components/UserSignupsPerMonthChart.vue
=> fix chart axis & text fill in dark mode

ui/src/services/mathbot-lang.js
@giftedprimate  Here is the new pull request.
=> Rewrote the syntax highlighters regex to handle more cases

ui/src/components/Bar.vue, ui/src/components/Commands.vue, ui/src/components/Edit_main.vue, ui/src/components/Function_drop.vue, ui/src/components/Robot.vue, ui/src/components/Staged_functions.vue, ui/src/components/UserGravatar.vue, ui/src/services/LevelControl.js
@giftedprimate Here is my pull request.
=> Mobile optimization

ui/src/components/Bar.vue, ui/src/components/Commands.vue, ui/src/components/Edit_main.vue, ui/src/components/Function_drop.vue, ui/src/components/Robot.vue, ui/src/components/Staged_functions.vue, ui/src/components/UserGravatar.vue, ui/src/services/LevelControl.js
Reverts JWWeatherman/math_bot#778
=> Revert "Mobile optimization"

ui/src/services/AuthService.js
=> user directed straight to /robot after authenticated
